### ISSUE TITLE
react-swipeable throws error using react 15.0.0

### ISSUE THREAD

**Issue by lo1tuma** [dogfessional/react-swipeable#31]
I’m trying to update my project to react 15.0.0 but `react-swipeable` throws the following error:

```
 TypeError: React.__spread is not a function
      at [object Object].React.createClass.render (node_modules/react-swipeable/js/Swipeable.js:149:40)
```

I think #26 would probably fix this problem as it removes the use of `React.__spread`.

**Comment by WhatFreshHellIsThis** [comment]
+1

**Comment by WhatFreshHellIsThis** [comment]
Apparently the react.__spread is coming back:
https://facebook.github.io/react/blog/2016/04/08/react-v15.0.1.html

"...   In order to make sure that code compiled with these tools is not broken, we will be restoring the React.__spread API and adding a warning. It will be removed in the future so if you maintain a project making using of it, we encourage you to compile to Object.assign directly or a similar helper function.  ..."

**Comment by WhatFreshHellIsThis** [comment]
Confirmed; react-swipeable works with react 15.0.1 (with the new deprecation warning)

**Comment by WhatFreshHellIsThis** [comment]
Just to be clear it works but it's annoying seeing that deprecation warning and obviously it's going to break as soon as they remove support for spread so a fix would be greatly appreciated.

**Comment by xiaolin** [comment]
same problem here seeing the warning.

**Comment by hartzis** [comment]
We are working on getting #26 merged in and publish which fixes this issue.

**Comment by SergeL** [comment]
👍

**Comment by hartzis** [comment]
fixed with 3.3.0
